language: c
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq curl
  - wget http://packages.madhouse-project.org/debian/add-release.sh
  - chmod +x add-release.sh
  - sudo ./add-release.sh syslog-ng-3.5
  - sudo apt-get update -qq
  - sudo apt-get install -qq aptitude
  - sudo aptitude install -q -y pkg-config flex bison liblua5.2-dev libmongo-client-dev syslog-ng-dev libperl-dev python-dev python3-dev libriemann-client-dev
before_script:
  - autoreconf -i
script:
  - ./modules/zmq/zmq_install.sh
  - autoreconf -vi
  - ./configure --enable-silent-rules
  - make
  - sudo make install
  - cd modules/zmq/scripts
  - ./zmq_test.sh with-pusher
compiler:
  - gcc
  - clang
notifications:
  email:
    recipients:
      - "lacienator@gmail.com"
    on_success: always
    on_failure: always
